package com.mjakobczyk.vrp.dynamic.impl.solution.impl.antcolony.model;

import com.mjakobczyk.vrp.model.Location;

import java.util.Collections;
import java.util.List;

/**
 * Ant represents a single worker that look for the best path in
 * {@link com.mjakobczyk.vrp.dynamic.impl.solution.impl.antcolony.AntColonyDynamicVrpSolutionProviderStrategy}.
 */
public class Ant {

    /**
     * inputLocations is a list of locations that are originally
     * contained in VrpInput.
     */
    private List<Location> inputLocations;

    /**
     * lastPath is a list of locations generated by Ant in the
     * last iteration.
     */
    private List<Location> lastPath;

    /**
     * Constructor of Ant that takes list of locations to visit.
     */
    public Ant(final List<Location> locations) {
        this.inputLocations = locations;
        this.lastPath = Collections.emptyList();
    }

    /**
     * Getter for lastPath.
     *
     * @return lastPath list
     */
    public List<Location> getLastPath() {
        return lastPath;
    }
}
